services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    networks:
      netbird-services:
        ipv4_address: ${APP_IP}
    environment:
      - DB_HOST=${DB_IP}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}:/var/www/html 
    restart: unless-stopped

  database:
    image: mariadb:lts-ubi9
    container_name: db
    networks:
      netbird-services:
        ipv4_address: ${DB_IP}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      netbird-services:
        ipv4_address: ${PMA_IP}
    environment:
      PMA_HOST: ${DB_IP}
      PMA_ARBITRARY: 1
    restart: unless-stopped

  mantis:
    image: xlrl/mantisbt:latest
    container_name: mantis
    environment:
      MANTIS_TIMEZONE: ${TZ}
      MANTIS_ENABLE_ADMIN: 1
    networks:
      netbird-services:
        ipv4_address: ${MANTIS_IP}
    volumes:
      - ${MANTIS_CONFIG_PATH}:/var/www/html/config
      - ${MANTIS_CUSTOM_PATH}:/var/www/html/custom
    restart: unless-stopped

# IMPORTANTE: Al final de tu archivo, asegúrate de registrar el nuevo volumen
volumes:
  db_data:
  mantis_config:

networks:
  netbird-services:
    external: true